export const teamMembers = [
  {
    name: "Jennifer Cooper",
    email: "siam.andrews@bcg.com",
    title: "Owner",
    company: "Boston Consulting Group (BCG)",
    office: "London Office",
    country: "United Kingdom",
    registerStatus: "Registered",
    image: "/icons/avatar.png",
    department: "Marketing",
  },
  {
    name: "Jennifer Cooper",
    email: "siam.andrews@bcg.com",
    title: "Owner",
    company: "Boston Consulting Group (BCG)",
    office: "London Office",
    country: "United Kingdom",
    registerStatus: "Registered",
    image: "/icons/avatar.png",
    department: "Marketing",
  },
  {
    name: "Jennifer Cooper",
    email: "siam.andrews@bcg.com",
    title: "Owner",
    company: "Boston Consulting Group (BCG)",
    office: "London Office",
    country: "United Kingdom",
    registerStatus: "Pending",
    department: "Marketing",
    image: "/icons/avatar.png",
  },
];
